# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Presentation
    url: presentation
    weight: 10
#  - name: News
#    url: post
#    weight: 20
#  - name: Trials
#    url: trial-and-error
  - name: People
    url: people
    weight: 30
  - name: Activities
    url: activities
    weight: 30
#  - name: Events
#  - name: Events
#    url: event
#    weight: 40
  - name: Publications
    url: publications
    weight: 50
  - name: Contact
    url: contact
    weight: 60
